#!/usr/bin/env python3
"""Generate assets/naming.json from the VA's filename generator spreadsheet.

The spreadsheet at assets/source/Ecoy_Photography_Filename_Generator.xlsx is the
SINGLE SOURCE for the photography vocabulary. When a colour or product is added
there, run this script and commit the regenerated naming.json. Never hand-edit
naming.json.

    python3 assets/build_naming.py
"""
import json, pathlib, openpyxl

ROOT = pathlib.Path(__file__).resolve().parent
XLSX = ROOT / "source" / "Ecoy_Photography_Filename_Generator.xlsx"

# Lists sheet column positions (1-indexed), verified against the workbook.
COLS = {
    "product": (1, 2),   # display, token
    "colour":  (4, 5),
    "angle":   (7, None),
    "people":  (9, None),
    "source":  (11, None),
    "ext":     (13, None),
    "pattern": (15, 16),
}
NA = {"(no colour / na)", "(none / na)", ""}


def read_lists(ws):
    out = {}
    for key, (dcol, tcol) in COLS.items():
        items = []
        for row in range(2, ws.max_row + 1):
            disp = ws.cell(row, dcol).value
            if disp is None or not str(disp).strip():
                continue
            disp = str(disp).strip()
            if disp.lower() in NA:
                continue
            tok = str(ws.cell(row, tcol).value or "").strip() if tcol else disp
            if not tok:
                continue
            items.append({"display": disp, "token": tok} if tcol else tok)
        out[key] = items
    return out


def build():
    wb = openpyxl.load_workbook(XLSX, data_only=True)
    L = read_lists(wb["Lists"])

    solid = [c for c in L["colour"] if not c["token"].endswith("Stripe")]
    stripe = [c for c in L["colour"] if c["token"].endswith("Stripe")]

    doc = {
        "$comment": "GENERATED by assets/build_naming.py from assets/source/Ecoy_Photography_Filename_Generator.xlsx. Do not hand-edit; edit the spreadsheet and re-run.",
        "version": "1.0",
        "library": {
            "master": "Google Drive, Ecoy shared drive",
            "root": "Photography",
            "rootFolderId": "18qRGqMBgXvmb-tKALvXgkPHhYuH6Setz",
            "rootUrl": "https://drive.google.com/drive/folders/18qRGqMBgXvmb-tKALvXgkPHhYuH6Setz",
            "note": "The repository never stores photography. Name the asset you need using the pattern below and pull it from Drive.",
            "cdn": {
                "pattern": "https://cdn.shopify.com/s/files/1/0498/6100/1367/files/{filename}",
                "note": ("Every image in library-index.json whose name appears in "
                         "shopify-upload-manifest.json is on the Shopify CDN under this pattern. "
                         "Shopify preserved filenames exactly (0 renames across 6,340 uploads), so "
                         "the url is derivable from the filename - no lookup table needed. Use these "
                         "urls in email, ads and web; they need no auth and are not rate limited."),
                "uploaded": "2026-09-22, 6340 of 6350 files",
            },
            "anglePreference": {
                "heroAndAds": "High45",
                "note": ("High45 is the preferred angle for advertising and hero creative. When "
                         "several frames of the same product and colour are available, rank High45 "
                         "first, then Low45, then Side. Sam's rule, 2026-09-21."),
            },
            "web": {
                "root": "Photography - Web",
                "rule": "Same relative path and filename stem as the master; only the root folder and the extension change.",
                "extension": ".webp",
                "longestEdge": 2400,
                "quality": 78,
                "typicalSize": "~237 KB, up to ~900 KB for texture-heavy close-ups, versus ~24 MB for a master",
                "preserves": "aspect ratio exactly, ICC colour profile, EXIF rotation baked in",
                "sourceExtensions": [".jpg", ".jpeg", ".png", ".tif", ".tiff"],
                "excludedFolders": ["NEW IMAGERY - to be renamed", "Archive", "Founder BTS & OLD Content"],
                "useFor": "screen work, mockups, anything on the web. Masters stay the source of truth for print and retouching.",
                "missingMeans": "not generated yet, not absent. Fall back to the master rather than erroring.",
                "hotlinking": "none. These are Drive files with no CDN in front of them, so they still cannot be referenced by URL from a published page.",
            },
        },
        "filename": {
            "pattern": "{product}-{pattern}-{colour}-{angle}-{people}-{source}-{seq}{ext}",
            "separator": "-",
            "example": "BambooSheetSet-Solid-Dusk-High45-NoTalent-Real-01.jpg",
            "exampleCombo": "BambooSheetSet-Solid-BurntOrangexWhite-High45-NoTalent-AI-01.jpg",
            "fields": {
                "product":  {"required": True,  "from": "products"},
                "pattern":  {"required": False, "from": "patterns", "omitWhen": "the product has no pattern (quilts, pillows, protector)"},
                "colour":   {"required": False, "from": "colours",  "omitWhen": "the product has no colourway", "combo": True},
                "angle":    {"required": True,  "from": "angles"},
                "people":   {"required": True,  "from": "people"},
                "source":   {"required": True,  "from": "sources"},
                "seq":      {"required": True,  "format": "two digits, zero padded, 01 upward"},
                "ext":      {"required": True,  "from": "extensions"},
            },
            "comboColour": {
                "rule": "A two-colour shot joins both tokens with a lowercase x and no spaces.",
                "format": "{colourA}x{colourB}",
                "example": "BurntOrangexWhite",
                "note": "Not in the spreadsheet dropdowns; built by hand. Order follows the Drive folder name.",
            },
        },
        "drivePath": {
            "pattern": "Photography/{Product display}/{Pattern}/{Colour folder}/{Talent folder}/{filename}",
            "talentFolders": {"NoTalent": "No Talent", "Talent": "Talent"},
            "note": "Folder names are human-formatted and keep spaces (Burnt Orange, No Talent). Filename tokens strip them (BurntOrange, NoTalent). Compare with spaces removed and case ignored.",
        },
        "products": L["product"],
        "patterns": L["pattern"],
        "colours": {"solid": solid, "stripe": stripe},
        "angles": L["angle"],
        "people": L["people"],
        "sources": L["source"],
        "extensions": L["ext"],
        "angleMeanings": {
            "High45": "45 degrees from above",
            "Low45": "45 degrees from low",
            "Overhead": "straight down, flat lay",
            "Side": "straight on from the side",
            "CloseUp": "fabric or detail crop",
            "Freestyle": "lifestyle or styled composition",
            "Deepetch": "cut out on transparent or white, for compositing",
        },
        "knownGaps": [
            "Polka is a valid pattern but has no Drive assets yet.",
            "Combo colours have no dropdown entry in the spreadsheet, so they are typed by hand.",
            "The spreadsheet's 'How to use' tab says Solo where every other tab and every real file says NoTalent.",
            "Files under 'NEW IMAGERY - to be renamed' do not follow this convention yet.",
            "Shopify product media uses no convention and cannot be resolved from a filename.",
        ],
    }
    (ROOT / "naming.json").write_text(json.dumps(doc, indent=2, ensure_ascii=False) + "\n")
    print(f"wrote naming.json: {len(doc['products'])} products, "
          f"{len(solid)} solid + {len(stripe)} stripe colours, {len(doc['angles'])} angles")


if __name__ == "__main__":
    build()
