#!/usr/bin/env python3
"""Build the repo's curated photography set from the Drive shortlist.

Claude Design can only read this repository, so a design that needs a real
Ecoy photograph needs the pixels here. This takes the human-curated shortlist
in "Photography - Web/Claude Photos", drops anything unusable, downscales to
1200px, and writes it into assets/library/ with a manifest.

Two kinds of file are deliberately NOT copied:
  - a retired colourway, so a design physically cannot show a dead SKU
  - a filename that does not parse, because it cannot be traced to a master

    python3 assets/build_shortlist.py [--max-edge 1200] [--quality 80]
"""
import json, os, pathlib, re, shutil, sys
from PIL import Image


def slug(name):
    """Slot folders become URL-safe, so a path can be used verbatim as a URL."""
    return re.sub(r"-+", "-", re.sub(r"[^a-z0-9]+", "-", name.lower())).strip("-")

ROOT = pathlib.Path(__file__).resolve().parent
SHORTLIST = pathlib.Path(os.path.expanduser(
    "~/Library/CloudStorage/GoogleDrive-sam@ecoy.com.au/Shared drives/Ecoy shared drive"
    "/Photography - Web/Claude Photos"))
OUT = ROOT / "library"


def arg(flag, default):
    return type(default)(sys.argv[sys.argv.index(flag) + 1]) if flag in sys.argv else default


def main():
    max_edge, quality = arg("--max-edge", 1200), arg("--quality", 80)
    if not SHORTLIST.exists():
        sys.exit(f"Shortlist not found at {SHORTLIST}")

    index = json.loads((ROOT / "library-index.json").read_text())
    by_stem = {pathlib.Path(r["path"]).stem: r for r in index["files"]}
    retired = set(json.loads((ROOT / "colour-status.json").read_text())["retired"])

    if OUT.exists():
        shutil.rmtree(OUT)
    kept, skipped = [], []

    for src in sorted(SHORTLIST.rglob("*.webp")):
        slot = src.relative_to(SHORTLIST).parts[0]
        stem = src.stem
        row = by_stem.get(stem)

        if row is None:
            skipped.append({"file": src.name, "slot": slot,
                            "why": "not in the library index; filename cannot be traced to a master"})
            continue
        if row.get("valid") is False:
            skipped.append({"file": src.name, "slot": slot,
                            "why": f"filename does not parse: {row.get('unknown')}"})
            continue
        if row.get("colour") in retired:
            skipped.append({"file": src.name, "slot": slot,
                            "why": f"{row['colour']} is a retired colourway"})
            continue

        dst = OUT / slug(slot) / src.name
        dst.parent.mkdir(parents=True, exist_ok=True)
        with Image.open(src) as im:
            im.thumbnail((max_edge, max_edge), Image.LANCZOS)
            im.save(dst, "WEBP", quality=quality, method=6)
            w, h = im.size

        entry = {"file": f"library/{slug(slot)}/{src.name}", "slot": slot,
                 "master": row["path"], "width": w, "height": h,
                 "bytes": dst.stat().st_size}
        for k in ("product", "pattern", "colour", "angle", "people", "source"):
            if row.get(k):
                entry[k] = row[k]
        if row.get("seen"):
            entry["seen"] = row["seen"]
        kept.append(entry)

    total = sum(e["bytes"] for e in kept)
    doc = {
        "$comment": ("GENERATED by assets/build_shortlist.py from the human-curated shortlist in "
                     "Drive at 'Photography - Web/Claude Photos'. These are the only photographs "
                     "in this repository. Everything else lives in Drive."),
        "maxEdge": max_edge, "quality": quality,
        "counts": {"kept": len(kept), "skipped": len(skipped),
                   "megabytes": round(total / 1e6, 2)},
        "slots": {s: sum(1 for e in kept if e["slot"] == s)
                  for s in sorted({e["slot"] for e in kept})},
        "skipped": skipped,
        "files": kept,
    }
    (ROOT / "library-shortlist.json").write_text(json.dumps(doc, indent=1) + "\n")

    print(f"kept {len(kept)} images, {total/1e6:.1f} MB at {max_edge}px")
    for s, n in doc["slots"].items():
        print(f"   {s:26s} {n}")
    if skipped:
        print(f"\nskipped {len(skipped)}:")
        for s in skipped:
            print(f"   {s['file']}\n      {s['why']}")


if __name__ == "__main__":
    main()
