#!/usr/bin/env python3
"""Build assets/cdn-catalog.json: a lookup table mapping
(product, pattern, colour, angle) -> Shopify CDN image urls.

Source of truth is shopify-upload-manifest.json, which already excludes
retired colourways and legacy/unparseable names (see its own $comment).
This script does not hit Drive, the network, or Shopify; it only reorganises
data already in the repo.

Never hand-edit cdn-catalog.json. Regenerate it after any upload run:
    python3 assets/build_cdn_catalog.py
"""
import json
from pathlib import Path
from collections import defaultdict

ASSETS = Path(__file__).parent

ANGLE_PREFERENCE = ["High45", "Low45", "Side", "Overhead", "Freestyle", "CloseUp", "Deepetch"]

# Known gaps as of 2026-09-23 (see memory: ecoy-photography-cdn-layer).
# 7 Iceberg files were skipped by a path mismatch, now fixed in the manifest
# but not yet re-run through the uploader. 3 AllSeasonsQuilt files were never
# produced by the webp conversion and need re-compressing first.
KNOWN_NOT_YET_LIVE = {
    "colour": {"Iceberg"},  # broader than the exact 7; safe, small set
}


def load(name):
    with open(ASSETS / name) as f:
        return json.load(f)


def main():
    manifest = load("shopify-upload-manifest.json")
    cdn_pattern = manifest["cdnPattern"]

    # product -> pattern (or "_none") -> colour (or "_none") -> angle -> [entries]
    index = defaultdict(lambda: defaultdict(lambda: defaultdict(lambda: defaultdict(list))))

    total = 0
    flagged_not_yet_live = 0

    for f in manifest["files"]:
        product = f.get("product") or "_unknown"
        pattern = f.get("pattern") or "_none"
        colour = f.get("colour") or "_none"
        angle = f.get("angle") or "_none"

        entry = {
            "url": cdn_pattern.replace("{name}", f["name"]),
            "filename": f["name"],
            "people": f.get("people"),
            "source": f.get("source"),
        }

        not_yet_live = colour in KNOWN_NOT_YET_LIVE.get("colour", set())
        if not_yet_live:
            entry["notYetLive"] = True
            flagged_not_yet_live += 1

        index[product][pattern][colour][angle].append(entry)
        total += 1

    # Sort each angle's candidates for determinism (people then source then filename)
    def sort_key(e):
        return (e.get("people") or "", e.get("source") or "", e["filename"])

    def freeze(d):
        if isinstance(d, defaultdict):
            d = {k: freeze(v) for k, v in d.items()}
        elif isinstance(d, dict):
            d = {k: freeze(v) for k, v in d.items()}
        elif isinstance(d, list):
            d = sorted(d, key=sort_key)
        return d

    catalog = {
        "$comment": (
            "GENERATED by assets/build_cdn_catalog.py from shopify-upload-manifest.json. "
            "Do not hand-edit. Structure: index[product][pattern|'_none'][colour|'_none'][angle] "
            "-> list of {url, filename, people, source}. 'notYetLive' true on an entry means the "
            "manifest lists it but the upload has not been confirmed (see naming.json knownGaps / "
            "memory ecoy-photography-cdn-layer) — callers should skip those and fall back."
        ),
        "cdnPattern": cdn_pattern,
        "shopDomain": manifest["shopDomain"],
        "anglePreference": ANGLE_PREFERENCE,
        "counts": {
            "totalEntries": total,
            "flaggedNotYetLive": flagged_not_yet_live,
            "products": len(index),
        },
        "index": freeze(index),
    }

    out_path = ASSETS / "cdn-catalog.json"
    with open(out_path, "w") as f:
        json.dump(catalog, f, indent=2)
        f.write("\n")

    print(f"Wrote {out_path} — {total} entries across {len(index)} products "
          f"({flagged_not_yet_live} flagged not-yet-live).")


if __name__ == "__main__":
    main()
